# Generated by Django 4.2.2 on 2023-06-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='name',
            new_name='center_name',
        ),
        migrations.RemoveField(
            model_name='center',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='center',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='center',
            name='user',
        ),
        migrations.AddField(
            model_name='center',
            name='end_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='end_minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='start_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='start_minute',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
