# Generated by Django 4.2.2 on 2023-06-15 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_center_center_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='end_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='center',
            name='end_minute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='center',
            name='start_hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='center',
            name='start_minute',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
