# Generated by Django 4.2.2 on 2023-06-16 05:05
from django.contrib.auth.models import Group, Permission
from django.db import migrations

def initialize_groups(apps, schema_editor):
    # Create a group for Admin users
    admin_group, created = Group.objects.get_or_create(name='Admin')

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_center_end_hour_alter_center_end_minute_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_groups),
    ]
