# Generated by Django 4.2.2 on 2023-06-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230616_0505'),
    ]

    operations = [
    ]
