# Generated by Django 4.2.2 on 2023-06-16 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_center_end_hour_alter_center_end_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='applicants',
            field=models.ManyToManyField(related_name='centers', to=settings.AUTH_USER_MODEL),
        ),
    ]
